package fake

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"path"
)

type ParsedFile struct {
	Generator     *Generator
	Ref           *ast.File
	GeneratedFile *ast.File
	PkgPath       string
	PkgName       string
	Imports       map[string]*PackageInfo
	UsedImports   map[string]struct{}
}

func NewParsedFile(gen *Generator, filename string) *ParsedFile {
	file, err := parser.ParseFile(gen.FileSet, filename, nil, parser.ParseComments)
	if err != nil {
		panic(fmt.Sprintf("Error parsing file: %v\n", err))
	}
	pkgPath, _ := GetPackagePath(gen.FileSet, filename)
	return &ParsedFile{
		Generator:   gen,
		Ref:         file,
		PkgPath:     pkgPath,
		PkgName:     file.Name.Name,
		Imports:     ParseImports(file.Imports),
		UsedImports: make(map[string]struct{}),
		GeneratedFile: &ast.File{
			Package: token.Pos(43),
			Name:    ast.NewIdent(gen.MockPackageName),
			Comments: []*ast.CommentGroup{
				{
					List: []*ast.Comment{
						{
							Slash: token.Pos(0),
							Text:  "// Code generated by mockgen. DO NOT EDIT.",
						},
					},
				},
			},
			Decls: []ast.Decl{
				&ast.GenDecl{
					Tok: token.IMPORT,
					Specs: []ast.Spec{
						&ast.ImportSpec{Path: &ast.BasicLit{Kind: token.STRING, Value: "\"fmt\""}},
						&ast.ImportSpec{Path: &ast.BasicLit{Kind: token.STRING, Value: "\"testing\""}},
						&ast.ImportSpec{Name: ast.NewIdent("mockSetup"), Path: &ast.BasicLit{Kind: token.STRING, Value: "\"github.com/sonalys/fake/boilerplate\""}},
					},
				},
			},
		},
	}
}

func (f *ParsedFile) ListInterfaces() []*ParsedInterface {
	var resp []*ParsedInterface
	// Iterate through the declarations in the file
	for _, decl := range f.Ref.Decls {
		decl, ok := decl.(*ast.GenDecl)
		if !ok || decl.Tok != token.TYPE {
			continue
		}
		for _, spec := range decl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			interfaceType, ok := typeSpec.Type.(*ast.InterfaceType)
			if !ok {
				continue
			}
			cur := &ParsedInterface{
				ParsedFile: f,
				Type:       typeSpec,
				Ref:        interfaceType,
				Name:       typeSpec.Name.Name,
			}
			cur.GenericsTypes, cur.GenericsNames = cur.GetGenericsInfo()
			resp = append(resp, cur)
		}
	}
	return resp
}

func (f *ParsedFile) Write(output string) error {
	interfaceList := f.ListInterfaces()
	for _, it := range interfaceList {
		f.GeneratedFile.Decls = append(f.GeneratedFile.Decls, it.GenerateStruct())
	}
	outputName := path.Join(output, "out.gen.go")
	file, err := CreateFileAndFolders(outputName)
	if err != nil {
		return err
	}
	return printer.Fprint(file, f.Generator.FileSet, f.GeneratedFile)
}
